Handle user code catching errors from require
endojs/endo pull request #1120
Opened 2022-03-16 14:19 UTC by naugtur

fixes #1116

2022-03-16 14:40 UTC, naugtur commented on packages/compartment-mapper/test/fixtures-cjs-compat/node_modules/defineprop/example-elliptic.js
> +defineCurve('secp256k1');
just prettier

2022-03-16 14:40 UTC, naugtur commented on packages/compartment-mapper/test/fixtures-cjs-compat/node_modules/defineprop/main.js
just prettier

2022-03-16 15:26 UTC, kriskowal requested changes
I think I would prefer to avoid the side-effects of attempting to initialize a module twice. As you suggest, capturing and rethrowing the error would suffice. Otherwise, this is a great fix.

2022-03-17 21:03 UTC, kriskowal commented
From our conversation out-of-band, consider dependency graph A imports B imports C. If you import A, you’re arranging for a working set that will initialize in order C, B, A. My expectation, which requires confirmation, is that if B were to throw an error during initialization, that error would contaminate A but not C. So, any subsequent import that depends on B or C would replay the same error, but A would be fine. No module should ever be initialized twice, or initialized at all if one of its dependencies failed to initialize.

2022-03-24 04:08 UTC, erights commented
> From our conversation out-of-band, consider dependency graph A imports B imports C. If you import A, you’re arranging for a working set that will initialize in order C, B, A. My expectation, which requires confirmation, is that if B were to throw an error during initialization, that error would contaminate A but not C. So, any subsequent import that depends on B or C would replay the same error, but A would be fine. No module should ever be initialized twice, or initialized at all if one of its dependencies failed to initialize.

I can confirm this. In addition, if a module that is within an import cycle throws an error, it contaminates everything in its cycle, even if some others had started earlier.

Put another way, any directed graph can be considered to be a directed acyclic graph of *strongly connected components*. A failure contaminates its own strongly connected component and all dependent strongly connected components.

2022-03-24 04:10 UTC, erights reviewed
This seems like a fine change, and is certainly well motivated. However, I'm going to defer any approval decision to @kriskowal .

2022-04-04 19:17 UTC, kriskowal approved these changes

2022-04-05 08:35 UTC, merged