fix(compartment-mapper): allow transforms to run on unknown languages
endojs/endo pull request #1371
Opened 2022-11-16 00:59 UTC by kumavis

this allowed me to add transforms for typescript files, that transform them into cjs modules.

The extension is used when the language is unknown. It still enforces that there is a parser for the language as a result of the transformations.

```js
const moduleTransforms = {
  // ...
    'extension:ts': async (bytes, specifier, location, packageLocation) => {
      let parserLanguage = 'cjs'
      const moduleRecord = {
        file: location.toString(),
        source: bytes.toString(),
      }
      await runMetaMaskTransforms(moduleRecord)
      const transformedSource = Buffer.from(moduleRecord.source, 'utf8')
      return { bytes: transformedSource, parser: parserLanguage }
    },
 }
 ```

2022-11-16 23:27 UTC, kriskowal requested changes
Needs a test that exercises the case where a module exists with an extension that is neither supported by the compartment-mapper nor provided by the user.

2022-12-12 21:06 UTC, kumavis commented on packages/compartment-mapper/src/link.js
>      if (has(transforms, language)) {
this could be a `while` loop instead

2022-12-12 22:05 UTC, kumavis commented on packages/compartment-mapper/src/link.js
>      if (has(transforms, language)) {
>   107:38  error  Unexpected `await` inside a loop  no-await-in-loop

2022-12-12 22:07 UTC, kumavis commented on packages/compartment-mapper/src/link.js
>      if (has(transforms, language)) {
hmm actually this would break for things that dont change the language type but expect to run only once and not infinite times... :skull:

2022-12-12 22:49 UTC, kumavis commented
alternate prefix could be `unknown:ts`

2022-12-13 21:02 UTC, kriskowal commented on packages/compartment-mapper/src/link.js
> +      language = languageForExtension[extension] || `extension:${extension}`;
I would also accept `|| extension` based on our out-of-band conversation yesterday.

2022-12-13 21:48 UTC, merged