feat(daemon): Ensure a single connection between peers
endojs/endo pull request #2217
Opened 2024-04-17 05:42 UTC by kriskowal

This feature ensures that any pair of pet dæmons will only be connected by a single CapTP connection to ensure that identical remoteable objects round-trip between them. In this framework it is necessary to solve the problem of “crossed hellos”, such that two nodes that simultaneous start up and suddenly wish to be connected to each other will race to create the first connection. One of these daemons must drop an established connection and invalidate incarnations that depend upon it. We settle this question by biasing the behavior based on the relative values of their node identifiers.

This does not solve the more general problem that three-party-hand-off would solve: a remoteable that takes a trip through a third party will not return as an identical object. This is necessary toward that end, but there will need to be shared state among all open CapTP sessions.

This also raises another problem not solved in this change: when the loser of the race to cross hellos abandons an incarnation, it should not merely delete the incarnation but should immediately reïncarnate the formula subgraph that depends upon it.

2024-04-18 21:58 UTC, rekmarks requested changes
Looks good, but we should probably add a test that conclusively demonstrates that we've solved crossed hellos (see inline comment). Also some nits.

2024-04-18 21:58 UTC, rekmarks commented on packages/daemon/src/remote-control.js
> +      ) => import('./types.js').RemoteControlState} */
Formatting issue:
```suggestion
     *   cancelled: Promise<never>,
     * ) => import('./types.js').RemoteControlState}
     */
```

2024-04-18 21:58 UTC, rekmarks commented on packages/daemon/src/remote-control.js
> +      ) => import('./types.js').RemoteControlState} */
Same formatting issue as above:
```suggestion
     *   cancelled: Promise<never>,
     * ) => import('./types.js').RemoteControlState}
     */
```

2024-04-18 21:58 UTC, rekmarks commented on packages/daemon/test/test-endo.js
All of these tests also pass on `master`. We should probably add a test for crossed hellos that passes here but fails on `master`.

2024-04-18 22:18 UTC, kriskowal commented on packages/daemon/test/test-endo.js
> +});
This test fails on master because master does not attempt to deduplicate the A->B and B<-A CapTP connections.

2024-04-19 00:09 UTC, kriskowal commented on packages/daemon/test/test-endo.js
> +});
I was mistaken. This was passing. I created a more specific test that exercised a hello from the remote and integrated the remote control into the provider.

2024-04-22 22:41 UTC, kriskowal commented on packages/daemon/test/test-endo.js
> -  await E(hostB).addPeerInfo(await E(hostA).getPeerInfo());
This explicitly aggravates a crossed-hello and results in data-lock. I would like to punt the general solution in hopes that daemons will rarely restart at the same time. I am aware that this is foolish in the long term, but crossed hellos are hard and time is running short for our proof-of-concept demo.

2024-04-23 17:20 UTC, rekmarks approved these changes
This is good for now 👍

2024-04-23 17:26 UTC, rekmarks commented on packages/daemon/src/remote-control.js
> +      remoteNodeId > localNodeId
@kriskowal did you say that the datalock happens about half the time? Observation: this will be true about half the time.

2024-04-23 20:19 UTC, merged