harden-exports error on 'function' keyword
endojs/endo pull request #2387
Opened 2024-07-29 10:48 UTC by turadg

_fixup_

## Description

The new `harden-exports` rule should not allow a function defined by the `function` keyword to be exported, because it can't really be hardened. The hoisting allows the value to be mutated by an import before it can be hardened.

### Security Considerations

improvement

### Scaling Considerations

none

### Documentation Considerations

none

### Testing Considerations

new tests

### Compatibility Considerations

bug fix

### Upgrade Considerations

not released yet

2024-07-29 17:14 UTC, kriskowal approved these changes
LGTM!

2024-07-29 17:28 UTC, merged

2024-07-29 20:18 UTC, gibson042 requested changes

2024-07-29 20:18 UTC, gibson042 commented on packages/eslint-plugin/lib/rules/harden-exports.js
> +                message: `Export '${exportNode.declaration.id.name}' should be a const declaration with an arrow function.`,
**BUT** note also that hoisting affects functions which are exported outside of their declarations, and such cases should still be caught be this rule:
<details><summary><code>function functionName() {}; export { functionName };</code></summary>

```js
$ cat entry.mjs 
import { spy } from './cycle-maker.mjs';

export function inlineExport() {}
Object.freeze(inlineExport);

function separatedExport() {}
export { separatedExport };
Object.freeze(separatedExport);

spy('entry module');


$ cat cycle-maker.mjs 
import * as entry from './entry.mjs';

export function spy (from) {
  console.log(`# in ${from}`);
  for (const [name, value] of Object.entries(entry)) {
    console.log(name, Object.isFrozen(value) ? 'frozen' : 'unfrozen');
  }
}

spy('cycle-creating import');


$ node entry.mjs 
# in cycle-creating import
inlineExport unfrozen
separatedExport unfrozen
# in entry module
inlineExport frozen
separatedExport frozen
```

</details>

So I think this aspect needs to follow the same pattern as "_should be followed by a call to 'harden'_" messages, with post hoc verification:
```js
      'Program:exit'() {
        const sourceCode = context.getSourceCode();
        for (const exportNode of exportNodes) {
          /** @type {string[]} */
          let exportNames = [];

          if (exportNode.declaration) {
            // `export default` or an export that creates one or more new bindings.
            // @ts-expect-error xxx typedef
            if (exportNode.declaration.declarations) {
              // `export let` or `export const` or `export var`.
              // @ts-expect-error xxx typedef
              for (const declaration of exportNode.declaration.declarations) {
                pushDeclaredNames(exportNames, declaration.id);
              }
            } else if (exportNode.declaration.id) {
              // Export of a function or class declaration.
              pushDeclaredNames(exportNames, exportNode.declaration.id);
            } else if (exportNode.declaration.type === 'Identifier') {
              // `export default identifierName`.
              pushDeclaredNames(exportNames, exportNode.declaration);
            } else if (!isPrimitiveLiteral(exportNode.declaration)) {
              // Probably a default export of pattern or expression that is not
              // a primitive literal like `null` or `42n`.
              context.report({
                node: exportNode,
                message: `Export is possibly not hardened.`,
              });
            }
          } else if (exportNode.specifiers && !exportNode.source) {
            // `export { name1, name2 as exportName2, ... }`.
            // We care about checking the *local* name for hardening.
            for (const spec of exportNode.specifiers) {
              pushDeclaredNames(exportNames, spec.local || spec.exported);
            }
          }

          // TODO: Refactor to iterate over sourceCode.ast.body *once* rather
          // than repeating it for each `export` (likely by replacing this
          // loop-body Set<exportName: string> with an outer
          // exports = Map<exportName: string, exportNode> and then checking if
          // each statement is either a FunctionDeclaration whose name is a key
          // in the exports map (warranting a hoisting complaint) or an
          // ExpressionStatement that hardens a key in the exports map (in
          // which case that export does not need a missing-harden complaint).
          const missingHardenCalls = new Set(exportNames);
          for (const exportName of exportNames) {
            for (const statement of sourceCode.ast.body) {
              // @ts-expect-error xxx typedef
              const { type, id, declaration, expression } = statement;
              if (
                (type === 'FunctionDeclaration' && id.name === exportName) ||
                // @ts-expect-error xxx typedef
                (type === 'ExportNamedDeclaration' && declaration.id?.name === exportName)
              ) {
                // Function declaration hoisting makes values accessible before
                // they can be hardened, and from other modules in cases of
                // cyclic imports.
                context.report({
                  node: exportNode,
                  message: `Exported name '${
                    exportName
                  }' should identify a non-hoisted function.`,
                  // TODO: Add a fixer to replace
                  // /(?<keywords>(async\s+)?function\s*([*]\s*|\s))(?<name>([^\s*(\\]|\\u)+)/
                  // with `const ${name} = ${keywords}` in the declaring
                  // statement.
                });
              }
              if (
                type === 'ExpressionStatement' &&
                expression.type === 'CallExpression' &&
                expression.callee.type === 'Identifier' &&
                expression.callee.name === 'harden' &&
                expression.arguments.length === 1 &&
                expression.arguments[0].type === 'Identifier' &&
                expression.arguments[0].name === exportName
              ) {
                missingHardenCalls.delete(exportName);
              }
            }
          }
          // TODO: Should each non-hardened export get its own complaint?
          if (missingHardenCalls.size > 0) {
            const noun = missingHardenCalls.size === 1 ? 'export' : 'exports';
            context.report({
              node: exportNode,
              message: `Named ${noun} '${missingHardenCalls.join(', ')}' should be followed by a call to 'harden'.`,
              fix: function (fixer) {
                const hardenCalls = missingHardenCalls
                  .map(name => `harden(${name});`)
                  .join('\n');
                return fixer.insertTextAfter(exportNode, `\n${hardenCalls}`);
              },
            });
          }
        }
      },
```
with <details open><summary>helpers</summary>

```js
isPrimitiveLiteral = node =>
  node.type === 'Literal' && Object(node.value) === node.value;

const pushDeclaredNames = (names, node) {
  if (node.type === 'Identifier') {
    names.push(node.name);
  } else if (node.type === 'AssignmentPattern') {
    pushDeclaredNames(names, node.left);
  } else if (node.type === 'ObjectPattern') {
    for (const prop of node.properties) {
      if (prop.value) pushDeclaredNames(names, prop.value);
      if (prop.type === 'RestElement') pushDeclaredNames(names, prop.argument);
    }
  } else if (node.type === 'ArrayPattern') {
    for (const el of declaration.elements) {
      if (!el) continue; // elision
      // Recurse on the `argument` of a RestElement or other Pattern nodes as-is.
      pushDeclaredNames(names, el.argument || el);
    }
  } else {
    throw Error('Unexpected declaration node', { cause: node });
  }
};
```

</details>

Note that the above also fixes incorrect handling of
* `export const { propName: exportName } = objWithPropName` (_**`prop.key.name`** of `propName: exportName` pulls propName, whereas we should pull **`prop.value.name`** to  ensure the presence of `harden(exportName)`_) and
* `export const { name, ...rest } = obj` (object rest) and
* `export const { name, parent: { subName } }` (nested patterns) and
* `export const [ exportName1, … ] = array` (_`declaration.id.type === 'ArrayPattern'` is just skipped entirely_)

all of which we should address, but not necessarily in this PR.

2024-07-30 04:00 UTC, gibson042 commented on packages/eslint-plugin/lib/rules/harden-exports.js
> +                message: `Export '${exportNode.declaration.id.name}' should be a const declaration with an arrow function.`,
#2390