feat(ses): permit Promise.prototype.try
endojs/endo pull request #2609
Opened 2024-10-23 20:09 UTC by erights

Closes: #2607 
Refs: #XXXX

## Description

"There is no do. There is only try."
       --Anti-Yoda

See also https://github.com/tc39/proposal-promise-try

### Security Considerations

none

### Scaling Considerations

none

### Documentation Considerations

one less divergence to document.

### Testing Considerations

none

### Compatibility Considerations

better

### Upgrade Considerations

nothing breaking.

- [ ] Update `NEWS.md` for user-facing changes.

2024-10-23 22:29 UTC, kriskowal requested changes
You beat me to it, but `Promise.try` needs to be on the constructor and not the prototype.

2024-10-23 22:30 UTC, kriskowal commented
I’m abandoning this change https://github.com/endojs/endo/commit/ec5a9b4f3b313ef66927b41728b3397f1714cf3a

2024-10-24 18:05 UTC, erights commented
> You beat me to it, but `Promise.try` needs to be on the constructor and not the prototype.

Doh! Fixed. PTAL

2024-10-24 20:37 UTC, kriskowal approved these changes

2024-10-24 21:32 UTC, merged