refactor(pass-style)!: Make @fast-check/ava a devDependency
endojs/endo pull request #2645
Opened 2024-11-22 00:30 UTC by gibson042

Fixes #1741

## Description

Rather than importing `fc` directly to export arbitraries, @endo/pass-style/tools.js now returns them from an exported `makeArbitraries` function that requires `fc` as an argument.

### Security Considerations

n/a

### Scaling Considerations

n/a

### Documentation Considerations

n/a

### Testing Considerations

n/a

### Compatibility Considerations

This is a breaking change, but only to @endo/pass-style/tools.js. All imports in this repository have been updated, and I didn't see any in [agoric-sdk](https://github.com/Agoric/agoric-sdk) or [agoric-3-proposals](https://github.com/Agoric/agoric-3-proposals), but if there are any then they will need similar updates.

### Upgrade Considerations

This only affects code intended for testing, and I'm disinclined to even mention it in NEWS.md.

2024-11-22 02:10 UTC, erights approved these changes
LGTM, nice!

2024-11-22 02:11 UTC, erights commented
Note to other reviewers: best to review diffs after hiding whitespace diffs

2024-11-22 14:00 UTC, dckc commented
Will the breaking change major version bump ripple thru the rest of endo packages? 

@kriskowal does this seem appropriate to you? We agonized about a similar situation not long ago. I don't recall clearly how similar.

2024-12-02 20:25 UTC, kriskowal requested changes
integration pr plz

2024-12-02 21:44 UTC, gibson042 commented
Updated the commit and PR description to remove the breaking-change indication.

2024-12-03 17:33 UTC, kriskowal approved these changes
satisfied. thank you.

for the record, was green in CI with integration with agoric-sdk https://github.com/Agoric/agoric-sdk/pull/10608

2024-12-03 18:40 UTC, merged