fix(compartment-mapper)!: invert keys/values of renames in captureFromMap
endojs/endo pull request #2667
Opened 2024-12-20 23:37 UTC by boneskull

BREAKING CHANGE: The `CaptureResult.compartmentRenames` record returned by `captureFromMap()` is now _new to old_; previously it was _old to new_.

This more accurately solves for the use case of `compartmentRenames`, because the main use case demands the record is inverted. We can plainly see this issue in `captureFromMap`'s test suite (which this change simplifies).

In a future change, [branded types](https://www.learningtypescript.com/articles/branded-types) could describe the distinction between key and value, which are currently both `string`.

> [!IMPORTANT]
>
> The only consumer of `captureFromMap` that I'm aware of is _me_, and _me_ doesn't need this to be SemVer major.

2025-01-08 00:26 UTC, kriskowal requested changes

2025-01-08 00:26 UTC, kriskowal commented on packages/compartment-mapper/src/capture-lite.js
> +    ),
I think we consume the same data as `compartmentRenames` in `archive-lite.js` in the new to old mapping order. That at least suggests both the map and inverse map are useful and the mistake is to favor one with the good name.

I am now noticing that `capture-lite.js` contains copypasta of `archive-lite.js` that I would like not to drift apart so we can eventually merge them.

May I propose that we merge these first, then augment this result object with both the map and comap? We could take the opportunity to deprecate `compartmentRenames` in favor of a more clear dual:

- `newToOldCompartmentNames`
- `oldToNewCompartmentNames`

2025-01-09 01:10 UTC, boneskull commented on packages/compartment-mapper/src/capture-lite.js
> +    ),
@kriskowal 

- `capture-lite` returns:
  ```ts
  {
    compartmentRenames: Record<string, string>,
    captureCompartmentMap: CompartmentMapDescriptor, 
    captureSources: Sources
  }
  ```
  and `archive-lite` returns:
  ```ts
  {
    archiveCompartmentMap: CompartmentMapDescriptor,
    archiveSources: Sources
  }
  ```
  IMO it'd make sense to call the common properties `compartmentMap` and `sources`, respectively (in addition to the two props you mention above).
- By deprecate you mean soft-deprecate? Emit warning? Throw? Document in `NEWS`?
- In your mind, does "merging" ultimately look like "delete one of these files", or remove the copied method, or keep both methods and alias one to the other, or..?
boneskull
- or would you rather I just push some code and we'll see?

2025-01-09 01:25 UTC, kriskowal commented on packages/compartment-mapper/src/capture-lite.js
> +    ),
By merge, I mean eliminate duplication in the implementation. That might mean extracting a utility module that both can depend upon, or if one depends on the entirety of the other, you can import the utilities from one or the other, making sure not to expose the utilities to the public package exports.

By deprecate, I mean jsdoc `@deprecated` so it shows up in lint but no runtime consequences.

2025-01-09 23:35 UTC, boneskull commented
@kriskowal I've applied the requested changes

2025-01-10 01:08 UTC, kriskowal approved these changes

2025-01-15 02:07 UTC, boneskull commented
will merge when 🟢

2025-01-16 22:38 UTC, merged