fix(compartment-mapper): Generate strict bundle
endojs/endo pull request #751
Opened 2021-05-27 04:58 UTC by kriskowal

Integration with Agoric SDK revealed that the SES bundle, now generated by the compartment-map bundler instead of rollup, by virtue of running under CommonJS rules, was not running in strict mode as is default for ESM. This invalidated SES lockdown which complained vigorously about `arguments` and `caller` properties on some of its own repaired functions. This addresses the issue by generating strict mode bundles.

The bundle as written is sufficient for our purpose but does not compose concatenatively, which is sometimes consider a good practice for UMD style bundles. I’m open to the option of wrapping the entire bundle in yet-another-IFFE if folks feel strongly about that invariant.

2021-05-27 04:59 UTC, kriskowal commented
Also open to ideas about how best to test this property. It might be necessary to increase the scope of this change to also subsume #740, which would probably cause the integration tests to fail before this fix.

2021-05-27 23:39 UTC, erights requested changes
Replaying conclusions from an offline chat with @kriskowal 

The concatenation issue does make me nervous. However, whether or not we change it to be tolerant of concatenation (with an IFEE), we need anyway a fail-fast test that fails if sloppy before any damage could possibly happen. Given that we have such a test, the IFEE does not make us any safer. It merely makes us tolerant of concatenation situations where we'd prefer to fail-fast rather than be tolerant.

So no IFEE, but we need that early test.

2021-05-27 23:41 UTC, erights commented
> Also open to ideas about how best to test this property. It might be necessary to increase the scope of this change to also subsume #740, which would probably cause the integration tests to fail before this fix.

Yes. Our conclusion means that this PR should subsume #740

2021-05-28 00:04 UTC, kriskowal commented
@erights prepended a commit to this change that addresses #740 (sloppy mode detector). I ran the integration test locally after adding the sloppy mode detector but before integrating a subsequent fix to the compartment-map bundler. As predicted, the sloppy mode detector would have caused the integration test to fail and the bug detected earlier.

2021-05-28 00:24 UTC, erights approved these changes
OMG the PR is 25x larger ;)

LGTM

2021-05-28 00:29 UTC, merged