fix(ses): Error cause permits
endojs/endo pull request #955
Opened 2021-12-10 22:20 UTC by kriskowal

The cause property on errors is now a stage 4 proposal and in evidence in the wild.

2021-12-14 00:57 UTC, mhofman requested changes
AFAIK, there are no implementations where `cause` is an accessor on the Error prototype, just a dummy `undefined` value in v8, probably to prevent the error object instances from shifting shape.

2021-12-14 00:57 UTC, mhofman commented on packages/ses/NEWS.md
> +- Updates the permits to include the `cause` accessor on all prototypes.
```suggestion
- Updates the permits to include `cause` placeholders on Error prototypes.
```

2021-12-14 01:21 UTC, mhofman commented on packages/ses/src/whitelist.js
> +    cause: 'undefined',
```suggestion
    cause: false,
```

Apparently it was a [bug](https://github.com/tc39/notes/blob/master/meetings/2021-10/oct-26.md#:~:text=However%2C%20Chrome%2093,and%20node%2016.11.) in v8's implementation to have included it in the first place:
> However, Chrome 93 and node 16.9 and 16.10 shipped with `cause` property on `Error.prototype` as well, which is not supposed to be there. It's technically allowed by the spec, but that was not the design of the feature or the intention and it's not what the other engines have chosen to do. And so, of course, that obvious bug was fixed in Chrome 94 and node 16.11.

2021-12-20 23:21 UTC, kriskowal commented
Notes: when I get back to this issue, the plan of record is to delete these properties in the repair phase instead of permitting them.

2022-01-06 01:50 UTC, kriskowal commented
I’ve posted a fresh attempt.

2022-01-06 02:14 UTC, mhofman approved these changes
I don't claim to understand the whitelist mechanism, but why isn't setting to `false` there not sufficient?

2022-01-06 03:50 UTC, kriskowal commented
@mhofman That is in fact the better solution. Posted a different commit to address the same issue, this time using a permit.

2022-01-06 07:04 UTC, erights approved these changes
LGTM

2022-01-06 08:01 UTC, merged